### PR TITLE
Support Single (32bit float)

### PR DESCRIPTION
**Pull request by kevinresol**

### CODE REVIEW

**Comment by kevinresol** [comment]
Note: Eval does not support `Single`

https://github.com/HaxeFoundation/haxe/blob/3520b3054cf721bce4839531830abc3c98ec652e/std/StdTypes.hx#L63-L68

**Comment by Aurel300** [comment]
Not sure if eval will survive as a target x)

**Comment by Aurel300** [comment]
Hmm, the CI was not set up to run on PRs. Should be fixed on master. Can you try to rebase or merge and see if that triggers the build?

**Comment by kevinresol** [comment]
Apparently Haxe generated different code for testFloats, causing the failure

Left: with Single: tmp vars are cast as `float`
Right: without Single: tmp vars are cast as `Float`
Screenshot 2020-06-22 at 10 24 09 AM

**Comment by Aurel300** [comment]
Thanks!

**Pull request merged**
